### ISSUE TITLE
None of the tests pass

### ISSUE THREAD

**Issue by aseanwatson** [rianadon/hass-taste-test#1]
First some background. I wanted to try hacking on the [timer-bar-card](https://github.com/rianadon/timer-bar-card), but its tests didn't pass (before I made any changes). It seemed to be related to a problem with this repo. I've got a bunch of experience with C#, C++, PowerShell, and SQL. But TypeScript/JavaScript and Python are not my strong point. It's entirely possible that this is user-error. Appologies in advance 🤷‍♂️.

# Steps:
I did this in a fresh LXC container `lxc launch ubuntu:focal mycontainer`:
```
#!/bin/bash
TMPDIR=/tmp/${0/*\//}_$$
trap "rm -r $TMPDIR" 0
mkdir -p "$TMPDIR"

cat > "$TMPDIR/setup.sh" << EOF
#!/bin/bash
apt update
apt upgrade -y
apt autoremove -y
apt install -y python3.8-venv python3-pip
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install node # "node" is an alias for the latest version
nvm use node
git clone https://github.com/rianadon/hass-taste-test.git
cd hass-taste-test
npm install --save-dev hass-taste-test jest jest-image-snapshot playwright
npx playwright install-deps
npx hass-taste-test
npm run test
EOF

CONTAINER=tastetest
# try to preserve the MAC address to avoid confusing my router's DHCP
HWADDR=$(lxc ls $CONTAINER -f json | jq -r '.[0].config["volatile.eth0.hwaddr"]')
if [ "$HWADDR" != null ]
then
        lxc stop --force $CONTAINER
        lxc delete --force $CONTAINER
        lxc launch ubuntu:focal $CONTAINER << EOF
config:
  volatile.eth0.hwaddr: $HWADDR
EOF
else
        lxc launch ubuntu:focal $CONTAINER
fi
sleep 3
lxc file push $TMPDIR/setup.sh $CONTAINER/tmp/
lxc exec $CONTAINER -- chmod +x /tmp/setup.sh
lxc exec $CONTAINER -- /tmp/setup.sh
lxc exec $CONTAINER -- rm /tmp/setup.sh
```

After churning a bit, I get this 5 times:

```
 FAIL  test/custom-component.jest.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/root/hass-taste-test/src/integrations/../../lib/integrations/get-diffable-html.js'

      4 | import { BrowserIntegration, BrowserPage, DashboardOptions, DiffOptions } from '../types'
      5 |
    > 6 | const htmlScript = readFileSync(__dirname + '/../../lib/integrations/get-diffable-html.js', 'utf-8')
        |                                ^
      7 |
      8 | export type PlaywrightElement = ElementHandle<Node>
      9 |

      at Object.<anonymous> (../src/integrations/playwright.ts:6:32)
      at Object.<anonymous> (../src/index.ts:18:1)

 FAIL  test/input_number.jest.ts
...repeat...
 FAIL  test/timer.jest.ts
...repeat...
 FAIL  test/sensor.jest.ts
...repeat...
 FAIL  test/custom-card.jest.ts
...repeat...

Test Suites: 5 failed, 5 total
Tests:       0 total
Snapshots:   0 total
Time:        4.699 s
Ran all test suites.
```

It seems `/root/hass-taste-test/src/integrations/../../lib/integrations/get-diffable-html.js` should be `/root/hass-taste-test/src/integrations/../../node_modules/hass-taste-test/lib/integrations/get-diffable-html.js`.

So, I made this change

``` diff
diff --git a/src/integrations/playwright.ts b/src/integrations/playwright.ts
index 7cf47ef..042aaae 100644
--- a/src/integrations/playwright.ts
+++ b/src/integrations/playwright.ts
@@ -3,7 +3,7 @@ import { chromium, webkit, firefox } from 'playwright'
 import { readFileSync } from 'fs'
 import { BrowserIntegration, BrowserPage, DashboardOptions, DiffOptions } from '../types'

-const htmlScript = readFileSync(__dirname + '/../../lib/integrations/get-diffable-html.js', 'utf-8')
+const htmlScript = readFileSync(__dirname + '/../../node_modules/hass-taste-test/lib/integrations/get-diffable-html.js', 'utf-8')

 export type PlaywrightElement = ElementHandle<Node>
```

I still see a bunch of failures:
* 2022-08-21 08:35:41 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.8.10 is deprecated and will be removed in Home Assistant 2022.1. Please upgrade Python to 3.9.
* 2022-08-21 08:35:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from localhost (127.0.0.1). (node-fetch/1.0 (+https://github.com/bitinn/node-fetch))
* 2022-08-21 08:35:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from localhost (127.0.0.1). (None)

```
    thrown: 2

      14 | expect.extend({ toMatchImageSnapshot })
      15 |
    > 16 | beforeAll(async () => {
         | ^
      17 |     hass = await HomeAssistant.create(CONFIGURATION_YAML, {
      18 |         browser: new PlaywrightBrowser(process.env.BROWSER || 'firefox'),
      19 |     })

      at Object.<anonymous> (timer.jest.ts:16:1)
```

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'close')

      20 | }, 30000)
      21 |
    > 22 | afterAll(async () => await hass.close())
         |                                 ^
      23 |
      24 | it('Timer element', async () => {
      25 |     const dashboard = await hass.Dashboard([{ type: 'entities', entities: ['timer.basic'] }])

      at timer.jest.ts:22:33
```

```
 FAIL  test/input_number.jest.ts (12.598 s)
  ● input_number slider

    Expected image to match or be a close match to snapshot but was 0.6069331526648599% different from snapshot (215 differing pixels).
    See diff for details: /home/sean/hass-taste-test/test/__image_snapshots__/__diff_output__/input-number-jest-ts-input-number-slider-3-diff.png

      45 |
      46 |     // BONUS: Image snapshot!
    > 47 |     expect(await dashboard.cards[0].screenshot()).toMatchImageSnapshot()
         |                                                   ^
      48 | })
      49 |
      50 | it('input_number box', async () => {

      at Object.<anonymous> (input_number.jest.ts:47:51)

  ● input_number slider

    expect(received).toMatchSnapshot()

    Snapshot name: `input_number slider 1`

    - Snapshot  - 4
    + Received  + 4

    @@ -2,15 +2,15 @@
        <ha-card outlined="false">
          <slot></slot>
          <div class="card-content" id="states">
            <div>
              <hui-input-number-entity-row>
    -           <hui-generic-entity-row config="[object Object]" no-secondary="">
    +           <hui-generic-entity-row config="[object Object]" hideName="false" no-secondary="">
    -             <state-badge _showIcon="true" stateObj="[object Object]">
    +             <state-badge _showIcon="true" class="pointer" stateObj="[object Object]" tabindex="0">
    -               <ha-icon data-state="30.0" icon="hass:ray-vertex" style="">…</ha-icon>
    +               <ha-state-icon data-state="30.0" style="">…</ha-state-icon>
                  </state-badge>
    -             <div class="info text-content" title="Slider">
    +             <div class="info pointer text-content" title="Slider">
                    Slider
                  </div>
                  <slot></slot>
                  <div class="flex">
                    <ha-slider aria-disabled="false" aria-valuemax="35" aria-valuemin="-20" aria-valuenow="30" dir="ltr" editable="false" id="input" ignore-bar-touch="" ignoreBarTouch="true" maxMarkers="0" pin="true" role="slider" secondaryProgress="0" snaps="false" tabindex="0" value="30">…</ha-slider>

      35 |         { type: 'entities', entities: ['input_number.slider1'] },
      36 |     ])
    > 37 |     expect(await dashboard.cards[0].html()).toMatchSnapshot()
         |                                             ^
      38 |     await hass.callService(
      39 |         'input_number',
      40 |         'set_value',

      at Object.<anonymous> (input_number.jest.ts:37:45)

  ● input_number slider

    expect(received).toMatchSnapshot()

    Snapshot name: `input_number slider 2`

    - Snapshot  - 4
    + Received  + 4

    @@ -2,15 +2,15 @@
        <ha-card outlined="false">
          <slot></slot>
          <div class="card-content" id="states">
            <div>
              <hui-input-number-entity-row>
    -           <hui-generic-entity-row config="[object Object]" no-secondary="">
    +           <hui-generic-entity-row config="[object Object]" hideName="false" no-secondary="">
    -             <state-badge _showIcon="true" stateObj="[object Object]">
    +             <state-badge _showIcon="true" class="pointer" stateObj="[object Object]" tabindex="0">
    -               <ha-icon data-state="5.0" icon="hass:ray-vertex" style="">…</ha-icon>
    +               <ha-state-icon data-state="5.0" style="">…</ha-state-icon>
                  </state-badge>
    -             <div class="info text-content" title="Slider">
    +             <div class="info pointer text-content" title="Slider">
                    Slider
                  </div>
                  <slot></slot>
                  <div class="flex">
                    <ha-slider aria-disabled="false" aria-valuemax="35" aria-valuemin="-20" aria-valuenow="5" dir="ltr" editable="false" id="input" ignore-bar-touch="" ignoreBarTouch="true" maxMarkers="0" pin="true" role="slider" secondaryProgress="0" snaps="false" tabindex="0" value="5">…</ha-slider>

      42 |         { entity_id: 'input_number.slider1' }
      43 |     )
    > 44 |     expect(await dashboard.cards[0].html()).toMatchSnapshot()
         |                                             ^
      45 |
      46 |     // BONUS: Image snapshot!
      47 |     expect(await dashboard.cards[0].screenshot()).toMatchImageSnapshot()

      at Object.<anonymous> (input_number.jest.ts:44:45)

  ● input_number box

    expect(received).toMatchSnapshot()

    Snapshot name: `input_number box 1`

    - Snapshot  - 4
    + Received  + 4

    @@ -2,15 +2,15 @@
        <ha-card outlined="false">
          <slot></slot>
          <div class="card-content" id="states">
            <div>
              <hui-input-number-entity-row>
    -           <hui-generic-entity-row config="[object Object]" no-secondary="">
    +           <hui-generic-entity-row config="[object Object]" hideName="false" no-secondary="">
    -             <state-badge _showIcon="true" stateObj="[object Object]">
    +             <state-badge _showIcon="true" class="pointer" stateObj="[object Object]" tabindex="0">
    -               <ha-icon data-state="30.0" icon="hass:ray-vertex" style="">…</ha-icon>
    +               <ha-state-icon data-state="30.0" style="">…</ha-state-icon>
                  </state-badge>
    -             <div class="info text-content" title="Numeric Input Box">
    +             <div class="info pointer text-content" title="Numeric Input Box">
                    Numeric Input Box
                  </div>
                  <slot></slot>
                  <div class="flex state">
                    <paper-input aria-disabled="false" auto-validate="" id="input" no-label-float="" pattern="[0-9]+([\.][0-9]+)?" tabindex="0" type="number" value="30">…</paper-input>

      50 | it('input_number box', async () => {
      51 |     const dashboard = await hass.Dashboard([{ type: 'entities', entities: ['input_number.box1'] }])
    > 52 |     expect(await dashboard.cards[0].html()).toMatchSnapshot()
         |                                             ^
      53 |     await hass.callService(
      54 |         'input_number',
      55 |         'set_value',

      at Object.<anonymous> (input_number.jest.ts:52:45)

  ● input_number box

    expect(received).toMatchSnapshot()

    Snapshot name: `input_number box 2`

    - Snapshot  - 4
    + Received  + 4

    @@ -2,15 +2,15 @@
        <ha-card outlined="false">
          <slot></slot>
          <div class="card-content" id="states">
            <div>
              <hui-input-number-entity-row>
    -           <hui-generic-entity-row config="[object Object]" no-secondary="">
    +           <hui-generic-entity-row config="[object Object]" hideName="false" no-secondary="">
    -             <state-badge _showIcon="true" stateObj="[object Object]">
    +             <state-badge _showIcon="true" class="pointer" stateObj="[object Object]" tabindex="0">
    -               <ha-icon data-state="5.0" icon="hass:ray-vertex" style="">…</ha-icon>
    +               <ha-state-icon data-state="5.0" style="">…</ha-state-icon>
                  </state-badge>
    -             <div class="info text-content" title="Numeric Input Box">
    +             <div class="info pointer text-content" title="Numeric Input Box">
                    Numeric Input Box
                  </div>
                  <slot></slot>
                  <div class="flex state">
                    <paper-input aria-disabled="false" auto-validate="" id="input" no-label-float="" pattern="[0-9]+([\.][0-9]+)?" tabindex="0" type="number" value="5">…</paper-input>

      57 |         { entity_id: 'input_number.box1' }
      58 |     )
    > 59 |     expect(await dashboard.cards[0].html()).toMatchSnapshot()
         |                                             ^
      60 | })
      61 |

      at Object.<anonymous> (input_number.jest.ts:59:45)

 › 5 snapshots failed.
```

```
 FAIL  test/custom-component.jest.ts (18.653 s)
  ● Custom Component Card

    Expected image to match or be a close match to snapshot but was 1.1578809336480462% different from snapshot (883 differing pixels).
    See diff for details: /home/sean/hass-taste-test/test/__image_snapshots__/__diff_output__/custom-component-jest-ts-custom-component-card-2-diff.png

      26 |     const card = dashboard.cards[0]
      27 |     expect(await card.html()).toMatchSnapshot()
    > 28 |     expect(await card.screenshot()).toMatchImageSnapshot()
         |                                     ^
      29 | })
      30 |

      at Object.<anonymous> (custom-component.jest.ts:28:37)

 › 1 snapshot failed.
```
```
 FAIL  test/custom-card.jest.ts (22.736 s)
  ● Custom Card

    thrown: 2

      11 | let hass: HomeAssistant<PlaywrightElement>
      12 |
    > 13 | beforeAll(async () => {
         | ^
      14 |     hass = await HomeAssistant.create(CONFIGURATION_YAML, {
      15 |         browser: new PlaywrightBrowser(process.env.BROWSER || 'firefox'),
      16 |     })

      at Object.<anonymous> (custom-card.jest.ts:13:1)


  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'close')

      17 |     await hass.addResource(__dirname + '/resources/custom-card.js', 'module')
      18 | }, 30000)
    > 19 | afterAll(async () => await hass.close())
         |                                 ^
      20 |
      21 | it('Custom Card', async () => {
      22 |     const dashboard = await hass.Dashboard([

      at custom-card.jest.ts:19:33

 FAIL  test/sensor.jest.ts (23.241 s)
  ● light theme

    Expected image to be the same size as the snapshot (492x94), but was different (492x93).
    See diff for details: /home/sean/hass-taste-test/test/__image_snapshots__/__diff_output__/sensor-jest-ts-light-theme-1-diff.png

      24 |     const dashboard = await hass.Dashboard([{ type: 'sensor', entity: 'sensor.test_sensor' }])
      25 |
    > 26 |     expect(await dashboard.cards[0].screenshot()).toMatchImageSnapshot()
         |                                                   ^
      27 | })
      28 |
      29 | it('dark theme', async () => {

      at Object.<anonymous> (sensor.jest.ts:26:51)

  ● dark theme

    Expected image to be the same size as the snapshot (492x94), but was different (492x93).
    See diff for details: /home/sean/hass-taste-test/test/__image_snapshots__/__diff_output__/sensor-jest-ts-dark-theme-1-diff.png

      32 |     })
      33 |
    > 34 |     expect(await dashboard.cards[0].screenshot()).toMatchImageSnapshot()
         |                                                   ^
      35 | })
      36 |

      at Object.<anonymous> (sensor.jest.ts:34:51)

 › 2 snapshots failed.
2022-08-21 08:35:55 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.8.10 is deprecated and will be removed in Home Assistant 2022.1. Please upgrade Python to 3.9.
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Snapshot Summary
 › 8 snapshots failed from 3 test suites. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 5 failed, 5 total
Tests:       8 failed, 8 total
Snapshots:   8 failed, 1 passed, 9 total
Time:        24.138 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
^C
```

Here are the images:

## custom-component-jest-ts-custom-component-card-2-diff
![custom-component-jest-ts-custom-component-card-2-diff](https://user-images.githubusercontent.com/105624573/185783319-981a05e2-c8d0-4848-bba2-9ee652bd86ee.png)

## input-number-jest-ts-input-number-slider-3-diff
![input-number-jest-ts-input-number-slider-3-diff](https://user-images.githubusercontent.com/105624573/185783328-c040ec79-2dbb-4d98-bed8-d7818bb3f8ea.png)

## sensor-jest-ts-dark-theme-1-diff
![sensor-jest-ts-dark-theme-1-diff](https://user-images.githubusercontent.com/105624573/185783335-bd603acc-8c50-45da-833e-6cc06c3463fb.png)

## sensor-jest-ts-light-theme-1-diff
![sensor-jest-ts-light-theme-1-diff](https://user-images.githubusercontent.com/105624573/185783339-36c73155-a4f4-4d47-98b0-5acfbcb44ddd.png)

**Comment by aseanwatson** [comment]
After the above PRs (#2 and #3), here are the failures:

```
> hass-taste-test@0.0.13 test
> jest && ava

 FAIL  test/custom-component.jest.ts (12.028 s)
  ● Custom Component Card

    thrown: 2

      12 | let hass: HomeAssistant<PlaywrightElement>
      13 |
    > 14 | beforeAll(async () => {
         | ^
      15 |     hass = await HomeAssistant.create(CONFIGURATION_YAML, {
      16 |         customComponents: [componentDir],
      17 |         browser: new PlaywrightBrowser(process.env.BROWSER || 'firefox'),

      at Object.<anonymous> (custom-component.jest.ts:14:1)


  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'close')

      20 |     await hass.addResource(cardFile, 'module')
      21 | }, 30000)
    > 22 | afterAll(async () => await hass.close())
         |                                 ^
      23 |
      24 | it('Custom Component Card', async () => {
      25 |     const dashboard = await hass.Dashboard([{ type: 'custom:scheduler-card' }])

      at custom-component.jest.ts:22:33

...
 FAIL  test/custom-card.jest.ts (19.107 s)
  ● Custom Card

    thrown: 2

      11 | let hass: HomeAssistant<PlaywrightElement>
      12 |
    > 13 | beforeAll(async () => {
         | ^
      14 |     hass = await HomeAssistant.create(CONFIGURATION_YAML, {
      15 |         browser: new PlaywrightBrowser(process.env.BROWSER || 'firefox'),
      16 |     })

      at Object.<anonymous> (custom-card.jest.ts:13:1)


  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'close')

      17 |     await hass.addResource(__dirname + '/resources/custom-card.js', 'module')
      18 | }, 30000)
    > 19 | afterAll(async () => await hass.close())
         |                                 ^
      20 |
      21 | it('Custom Card', async () => {
      22 |     const dashboard = await hass.Dashboard([

      at custom-card.jest.ts:19:33

 PASS  test/input_number.jest.ts (19.54 s)
...
 PASS  test/timer.jest.ts (26.513 s)
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 2 failed, 3 passed, 5 total
Tests:       2 failed, 6 passed, 8 total
Snapshots:   12 passed, 12 total
Time:        27.346 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by aseanwatson** [comment]
On further investigation, the part covered in PR #2 is user error.

``` diff
diff --git a/src/integrations/playwright.ts b/src/integrations/playwright.ts
index 7cf47ef..042aaae 100644
--- a/src/integrations/playwright.ts
+++ b/src/integrations/playwright.ts
@@ -3,7 +3,7 @@ import { chromium, webkit, firefox } from 'playwright'
 import { readFileSync } from 'fs'
 import { BrowserIntegration, BrowserPage, DashboardOptions, DiffOptions } from '../types'

-const htmlScript = readFileSync(__dirname + '/../../lib/integrations/get-diffable-html.js', 'utf-8')
+const htmlScript = readFileSync(__dirname + '/../../node_modules/hass-taste-test/lib/integrations/get-diffable-html.js', 'utf-8')

 export type PlaywrightElement = ElementHandle<Node>
```

My script for running the tests should have been:

```diff
 git clone https://github.com/rianadon/hass-taste-test.git
 cd hass-taste-test
-npm install --save-dev hass-taste-test jest jest-image-snapshot playwright
+npm install --save-dev jest jest-image-snapshot playwright typescript
+npx tsc
 npx playwright install-deps
-npx hass-taste-test
+node lib/bin.js
 npm run test
```

I closed that PR and added more comments.

However, the snapshots still need updating per PR #3.

There are also some tests failing. After debugging, I discovered that the "2" is `ERR_INVALID_AUTH`.

I made a temporary change to get more information from the test run:
``` diff
iff --git a/src/socket.ts b/src/socket.ts
index 766245c..21b725f 100644
--- a/src/socket.ts
+++ b/src/socket.ts
@@ -19,7 +19,7 @@ const MSG_TYPE_AUTH_OK = 'auth_ok'
 const ERR_CANNOT_CONNECT = 1
 const ERR_INVALID_AUTH = 2
 
-const DEBUG = false
+const DEBUG = true
 
 export function createSocket(auth: Auth, ignoreCertificates: boolean): Promise<any> {
     // Convert from http:// -> ws://, https:// -> wss://
```

```TypeScript
        const handleMessage = (event: { data: any; type: string; target: WebSocket }) => {
            const message = JSON.parse(event.data)

            if (DEBUG)
                console.log(`[Auth phase] Received a message of type ${message.type}`, message)

            switch (message.type) {
                case MSG_TYPE_AUTH_INVALID:
                    invalidAuth = true
                    socket.close()
                    break

```
We're getting `{"type": "auth_invalid", "message": "Invalid access token or password"}` back. I haven't been able to investigate why.

**Comment by rianadon** [comment]
The work to run this in a container looks awesome!

I took a look; the issue is that the module tries to login before onboarding is initialized.
I need a better `isUp()` check, but for now I fixed the issue by retrying login; eventually, the onboarding component will initialize and the login will succeed.

**Comment by rianadon** [comment]
I've also added a [Developing](https://github.com/rianadon/hass-taste-test#developing) section to the README with how I test this repository. It's pretty similar to the steps you found on your own—sorry you had to go through that pain of figuring out which commands to run.
